name: Build and publish Docker Hub dev image

on:
  push:
    branches:
      - 'development'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.KARTAT_DOCKERHUB_USER }}
          password: ${{ secrets.KARTAT_DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hsldevcom/hsl-map-generator-server

      - name: Get commit hash
        id: commit_hash
        run: echo "hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Get image timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build and push timestamped tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ format('hsldevcom/hsl-map-generator-server:dev-{0}-{1}', steps.timestamp.outputs.timestamp, steps.commit_hash.outputs.hash) }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hsldevcom/hsl-map-generator-server:dev
